### ISSUE TITLE
Auth0 "enable" button is below the fold and the modal is not scrollable

### ISSUE THREAD

**Issue by cartogram** [graphcool/console#290] opened 2016-10-22 15:14 UTC
I am using a 13inch Macbook 2015.

The three fields required to configure Auth0 push the modal controls off the screen and I can't scroll to them. Perhaps position them absolutely to the bottom of the modal, set the height of the other div above it using `calc(100% - $height-of-modal-contols)`, and set the overflow to scroll.

**Comment by schickling** [comment] 2016-10-27 18:53
Closing this issue as it's an duplicate of #257

**Closed by schickling** 2016-10-27 18:53 UTC
Labels: area/models, bug, UI
