### ISSUE TITLE
Wrong Model name checker

### ISSUE THREAD

**Issue by brene** [graphcool/console#260] opened 2016-10-11 13:25 UTC
![image](https://cloud.githubusercontent.com/assets/4989523/19271921/f35e84ea-8fc6-11e6-89e3-8e3bcc896f60.png)
Even though it is marked "red" indicating the name is wrong, I'm still able to create that model.

**Comment by marktani** [comment] 2016-10-11 19:55
I thought about this aspect of our current validation before. Does it make
sense to extract validation and converting input data to the correct format
from the backend and the frontend into an independent module or is this
target overkill? This would prevent issues like these (this is not the
first one of this kind).

**Comment by brene** [comment] 2016-10-11 19:59
Maybe we can also just specify the regex in the system API GraphQL schema? Does that make sense? We can slowly make Graphcool Graphcool-Turing-Complete

**Comment by schickling** [comment] 2016-10-11 20:43
@sorenbs what do you think?

**Comment by sorenbs** [comment] 2016-10-12 13:28
@marktani I think that is too much infrastructure for something that shouldn't change often. The backend has one class where all the constraints are defined. If the dashboard has a similar central place that handle name validation rules, I think we can just make sure to keep it in sync.

Worth noting in this particular case the model name constraint in the dashboard is actually correct, but there is a separate rule to decide the background color.

One other thing - We discovered yesterday that we need to add a blacklist containing Node, Query, Mutation as well as all scalar types such as String as these are predefined in the schema. So let's make sure it is all synced up when we introduce this :-)

**Comment by christrotter89** [comment] 2016-10-26 23:49
I note that I can't create a model name that has been reserved by another user. Is this intended behaviour? Could be an issue when scaling.

**Comment by sorenbs** [comment] 2016-10-27 07:13
Hi @christrotter89 

There is no shared state between projects in the same account or between accounts. I have sent you a message on slack so we can figure out what is causing your issue :-)

**Comment by christrotter89** [comment] 2016-10-27 08:51
@sorenbs Sorry I actually was referring to Project, rather than model name. I believe the original demo project was auto deleted meaning I can now create the original Project name. Are Project names shared by the entire user pool?

**Comment by christrotter89** [comment] 2016-10-27 08:52
I would just like to add a UX point here. When adding a model from the dashboard, if I want to abandon creating the model, I should be able to press escape, or there should be a cancel button. The input field should then disappear.

**Comment by sorenbs** [comment] 2016-10-27 08:57
Ahh.

Project names have to be unique within the same user account. There is no restriction across users though. For example every single account has a project called Example Project :-)

For the UX point - we have an update to the sidebar that addresses this. We will probably release it today or tomorrow. Thanks for bringing it up!

**Comment by timsuchanek** [comment] 2016-10-28 14:25
Fixed in the new UI

**Closed by timsuchanek** 2016-10-28 14:25 UTC
Labels: area/sidebar, bug, priority/P2
