### ISSUE TITLE
Field popup: allow migration value when changing from non-list to list

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#222] opened 2016-09-28 08:56 UTC
I changed existing field to list

The error tells me that I should provide a migration value but the ui doesn't let me

![image](https://cloud.githubusercontent.com/assets/281337/18907000/254ca386-856a-11e6-97eb-352a14d81ddd.png)

**Comment by timsuchanek** [comment] 2016-11-01 16:58
Duplicate of #195

**Closed by timsuchanek** 2016-11-01 16:58 UTC
Labels: area/models/schema, bug, priority/P0
