### ISSUE TITLE
Hide/move/loose/change/kill the chat button

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/console#1158] opened 2017-06-22 21:04 UTC
**Do you want to request a *feature* or report a *bug*?**  
Feature/bug

**What is the current behavior?**
The chat button overlays crucial parts of the screen (the log button for the bottom function, the download json button in the playground, etc.)

**What is the expected behavior?**
Not pixel-fighting with the chat button to click just next to it to access what's underneath :)

**Which browser and OS are affected by this issue? Did this work in previous versions of the Console?**
Win 7 Ent SP1 (64-bit)
Chrome 58.0.3029.110 (64-bit)

**Comment by marktani** [comment] 2017-06-22 21:06
Closing as duplicate of https://github.com/graphcool/ui-feedback/issues/3.

**Closed by marktani** 2017-06-22 21:06 UTC
