### ISSUE TITLE
Console stops working after deleting project

### ISSUE THREAD

**Issue by tobiastornros** [graphcool/console#1286] opened 2017-08-16 12:34 UTC
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

Console stops working after deleting project.

**If the current behavior is a bug, please provide the steps to reproduce and if possible screenshots.**

Delete project in the settings panel.

<img width="1920" alt="graphcoolconsole" src="https://user-images.githubusercontent.com/17402497/29363324-d5fc8b88-828f-11e7-8d51-3cca96e0c189.png">

**What is the expected behavior?**

Should redirect to confirmation view or to console root. 

**Which browser and OS are affected by this issue? Did this work in previous versions of the Console?**

Chrome 60.x Mac OS X

**Comment by marktani** [comment] 2017-08-16 12:35
Thanks for the report! Very similar to #784.

**Comment by marktani** [comment] 2017-09-19 16:53
deleting as duplicate of https://github.com/graphcool/graphcool/issues/565.

**Closed by marktani** 2017-09-19 16:53 UTC
Labels: bug, priority/medium, UX
