### ISSUE TITLE
Endpoint popups can be opened infinite amount of times

### ISSUE THREAD

**Issue by brene** [graphcool/console#320] opened 2016-10-27 19:00 UTC
![oct-27-2016 21-00-21](https://cloud.githubusercontent.com/assets/4989523/19781176/70342a9c-9c88-11e6-8516-f5a4b2075cde.gif)

**Comment by schickling** [comment] 2016-10-28 08:36
Duplicate of #308

**Closed by schickling** 2016-10-28 08:36 UTC
